name: Bilet Otomasyon

on:
  workflow_dispatch   # ðŸ‘ˆ SADECE ELLE RUN

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Paketleri kur
        run: pip install pandas requests gspread google-auth openpyxl

      - name: Script Ã§alÄ±ÅŸtÄ±r
        env:
          BUBILET_TOKEN: ${{ secrets.BUBILET_TOKEN }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          APPS_SCRIPT_URL: ${{ secrets.APPS_SCRIPT_URL }}
        run: python main.py