name: Bilet Otomasyon

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # her saat başı

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Repo çek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Paketleri kur
        run: pip install -r requirements.txt

      - name: Script çalıştır
        run: python main.py
        env:
          BUBILET_TOKEN: ${{ secrets.BUBILET_TOKEN }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          