name: Bilet Otomasyon

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"   # ⏱️ 5 DAKİKADA BİR (GitHub Actions limiti)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Paketleri kur
        run: pip install pandas requests gspread google-auth openpyxl

      - name: Script çalıştır
        env:
          BUBILET_TOKEN: ${{ secrets.BUBILET_TOKEN }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: python main.py
