name: Bilet Otomasyon

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Paketleri kur
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Script çalıştır
        env:
          BUBILET_EMAIL: ${{ secrets.BUBILET_EMAIL }}
          BUBILET_PASSWORD: ${{ secrets.BUBILET_PASSWORD }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python main.py
